# Generated by Django 4.2.2 on 2023-06-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.TextField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
